package com.testspace.amer.taiftourguide;

import android.content.Intent;
import android.os.Bundle;
import android.support.annotation.NonNull;
import android.support.annotation.Nullable;
import android.support.v4.app.Fragment;
import android.support.v7.widget.LinearLayoutManager;
import android.support.v7.widget.RecyclerView;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;

import java.util.ArrayList;

public class ParksFragment extends Fragment implements PlaceAdapter.OnItemPressedListener {
    View rootView;
    RecyclerView recyclerView;
    ArrayList<Place> places;
    PlaceAdapter placeAdapter;

    public ParksFragment() {
    }

    @Nullable
    @Override
    public View onCreateView(@NonNull LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        rootView = inflater.inflate(R.layout.fragment_layout, container, false);
        recyclerView = rootView.findViewById(R.id.recyclerView);
        recyclerView.setLayoutManager(new LinearLayoutManager(getContext()));
        places = new ArrayList<>();
        placeAdapter = new PlaceAdapter();
        places.add(new Place(R.drawable.wahbah,
                "Al Wahbah crater",
                "The Al Wahbah crater is a volcanic crater, which is about 250 Km away from Taif.",
                "The Al Wahbah crater (Maqla Tamia in Arabic) is a volcanic crater, which is about 250 kilometers away from Taif, Saudi Arabia, on the western edge of the Harrat Kishb basalt plateau. The Harrat Kishb plateau contains many volcanic cones. It is 250 m (820 ft) deep and 2 km (1.2 mi) in diameter. The bottom of the crater is covered with white sodium phosphate crystals.\n\nIt takes a person 45-60 minutes to go to the bottom of the crater. This crater is very slippery and it is hard for people to come up to the surface. To climb back up takes approx 60-90 minutes. There is some mobile phone signal within the crater, and the site receives very few visitors indeed, even over weekends.\n\nWhile it was thought for some time that the crater was formed by a meteorite, as its appearance resembles that of the Barringer Crater, with its circular form and high sides, it is now commonly accepted by geologists that the crater is a maar crater, and was formed by volcanic activity in the form of an underground phreatic eruption – a massive steam explosion generated by molten basaltic magma coming into contact with subterranean water.",
                Place.NO_PHONE,
                "All week: 24 Hours.",
                "22.901072,41.139164"));
        places.add(new Place(R.drawable.daka,
                "Jabal Daka",
                "Jabal Daka (Dhaka Mount), is the highest mountain in the city of Taif, located in the west of Saudi Arabia.",
                "The mountain is located 20 kilometers south-west of Taif. It overlooks the Shifa tourist center. The mountain is used to know the dates of prayer, fasting, and breakfast in the month of Ramadan. The vegetation of the mountain is covered with juniper trees, the plant covers the bottom of the mountain and then gradually thins out until it reaches the top. The temperature of the top reaches below 0°C in the winter. The mountain has a tourist resort just 7 km away from the Shifa.",
                Place.NO_PHONE,
                "All week: 24 Hours.",
                "21.093586,40.291441"));
        places.add(new Place(R.drawable.rudaf,
                "Al Rudaf Park",
                "A large natural park in the south of Taif.",
                "A large natural park in the south of Taif where trees stand amidst magnificent weathered granite rocks. Good place for family and friends to relax, enjoy and play, it has basketball courts, football grounds with sitting place for spectators, Families can enjoy sitting in the park, children and young boys can play\nIt's a Beautiful, well-maintained place. No entry fee and all the playing areas inside are free.",
                Place.NO_PHONE,
                "Sunday: Closed.\nOther days: 4 PM - 2 AM.",
                "21.229756,40.424883"));
        places.add(new Place(R.drawable.saiysad,
                "Saiysad National park",
                "A huge park contains a very nice natural views.",
                "It’s a good place to visit if you have time in hand and have nothing to do on that day. There are a lot of gates present all around the park but you can get in only through one of them. However, traveling in large groups is recommended as the place is kind of isolated. Strolling around this park could be fun if you have kids. There are a few slides and some swings that your children can enjoy on.",
                Place.NO_PHONE,
                "All week: 24 Hours.",
                "21.293441,40.494085"));
        return rootView;
    }

    @Override
    public void onViewCreated(@NonNull View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        getActivity().setTitle("Attractions And Parks");
        placeAdapter.setPlaces(places);
        placeAdapter.setListener(this);
        recyclerView.setAdapter(placeAdapter);
    }

    @Override
    public void onItemClick(Place place) {
        Intent intent = new Intent(getActivity(), PlaceActivity.class);
        intent.putExtra("PLACE", place);
        startActivity(intent);
    }
}