///////////////////////////////////////////PARKS/////////////////////////////////////////////////////////
places.add(new Place(R.drawable.wahbah,
                "Al Wahbah crater",
                "The Al Wahbah crater is a volcanic crater, which is about 250 Km away from Taif.",
                "The Al Wahbah crater (Maqla Tamia in Arabic) is a volcanic crater, which is about 250 kilometers away from Taif, Saudi Arabia, on the western edge of the Harrat Kishb basalt plateau. The Harrat Kishb plateau contains many volcanic cones. It is 250 m (820 ft) deep and 2 km (1.2 mi) in diameter. The bottom of the crater is covered with white sodium phosphate crystals.\n\nIt takes a person 45-60 minutes to go to the bottom of the crater. This crater is very slippery and it is hard for people to come up to the surface. To climb back up takes approx 60-90 minutes. There is some mobile phone signal within the crater, and the site receives very few visitors indeed, even over weekends.\n\nWhile it was thought for some time that the crater was formed by a meteorite, as its appearance resembles that of the Barringer Crater, with its circular form and high sides, it is now commonly accepted by geologists that the crater is a maar crater, and was formed by volcanic activity in the form of an underground phreatic eruption – a massive steam explosion generated by molten basaltic magma coming into contact with subterranean water.",
                Place.NO_PHONE,
                "All week: 24 Hours.",
                "22.901072,41.139164"));
///////////////////////////////////////////////////////////////////////////////////
places.add(new Place(R.drawable.daka,
                "Jabal Daka",
                "Jabal Daka (Dhaka Mount), is the highest mountain in the city of Taif, located in the west of Saudi Arabia.",
                "The mountain is located 20 kilometers south-west of Taif. It overlooks the Shifa tourist center. The mountain is used to know the dates of prayer, fasting, and breakfast in the month of Ramadan. The vegetation of the mountain is covered with juniper trees, the plant covers the bottom of the mountain and then gradually thins out until it reaches the top. The temperature of the top reaches below 0°C in the winter. The mountain has a tourist resort just 7 km away from the Shifa.",
                Place.NO_PHONE,
                "All week: 24 Hours.",
                "21.093586,40.291441"));
///////////////////////////////////////////////////////////////////////////////////
places.add(new Place(R.drawable.rudaf,
                "Al Rudaf Park",
                "A large natural park in the south of Taif.",
                "A large natural park in the south of Taif where trees stand amidst magnificent weathered granite rocks. Good place for family and friends to relax, enjoy and play, it has basketball courts, football grounds with sitting place for spectators, Families can enjoy sitting in the park, children and young boys can play\nIt's a Beautiful, well-maintained place. No entry fee and all the playing areas inside are free.",
                Place.NO_PHONE,
                "Sunday: Closed.\nOther days: 4 PM - 2 AM.",
                "21.229756,40.424883"));
///////////////////////////////////////////////////////////////////////////////////
places.add(new Place(R.drawable.saiysad,
                "Saiysad National park",
                "A huge park contains a very nice natural views.",
                "It’s a good place to visit if you have time in hand and have nothing to do on that day. There are a lot of gates present all around the park but you can get in only through one of them. However, traveling in large groups is recommended as the place is kind of isolated. Strolling around this park could be fun if you have kids. There are a few slides and some swings that your children can enjoy on.",
                Place.NO_PHONE,
                "All week: 24 Hours.",
                "21.293441,40.494085"));
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////RES//////////////////////////////////////////
places.add(new Place(R.drawable.albaik,
                "Albaik",
                "Albaik's vision: Putting MMMMMs and WOOOWs on our customers’ lips, every time, everywhere, the world over.",
                "Al Baik is a major fast food restaurant chain in Saudi Arabia that primarily sells broasted chicken and shrimp with a variety of sauces. It is one of the major consumers of chicken in Saudi Arabia.\n\nCuisine:  Fast Food, Halal.\nMeals:  Lunch, Dinner.\nRestaurant features:  Takeout, Seating.\nGood for:  Kids, Families with children.",
                "+966122866777",
                "Friday: 1 PM - 12 AM.\nOther days: 10 AM - 12 AM.",
                "21.510695,40.487277"));
///////////////////////////////////////////////////////////////////////////////////
places.add(new Place(R.drawable.hirrman1,
                "Hirrman Restaurant",
                "Best restaurant serves Saleeq Saudi traditional meal in Taif.",
                "Cuisine:  Traditional, Deserts.\nMeals:  Lunch, Dinner.\nRestaurant features:  Takeout, Seating.\nGood for:  Families with children.",
                "+966127377272",
                "All week: 10 AM - 2 AM.",
                "21.268522,40.400665"));
///////////////////////////////////////////////////////////////////////////////////
places.add(new Place(R.drawable.mabshoor,
                "Mabshoor Al Taif",
                "Best restaurant in the Taif city if you are a meat lover.",
                "Cuisine:  Traditional, Grills, Deserts.\nMeals:  Lunch, Dinner.\nRestaurant features:  Takeout, Seating.\nGood for:  Large groups, Families with children.",
                "+966555722459",
                "All week: 1 PM - 3 PM, 6 PM - 12 AM.",
                "21.287296,40.423130"));
///////////////////////////////////////////////////////////////////////////////////
places.add(new Place(R.drawable.mirage,
                "Mirage",
                "From food quality and cost perspective, it is the best Indian restaurant in Taif.",
                "Cuisine:  Indian, Asian, Vegetarian-Friendly, Vegan Options.\nMeals:  Dinner, Brunch, Lunch.\nRestaurant features:  Takeout, Seating, Waitstaff.\nGood for:  Large groups, Families with children.",
                "+966127484444",
                "Sunday: 1 PM - 12 AM.\nOther days: 1 PM - 1 AM.",
                "21.233262,40.410999"));
///////////////////////////////////////////////////////////////////////////////////
places.add(new Place(R.drawable.vitamin,
                "Vitamin Palace",
                "Specialize in wide varieties of delicious fresh Juices and fast food.",
                "Cuisine:  Middle Eastern, Deserts, Fast Food.\nMeals:  Lunch, Dinner.\nRestaurant features:  Takeout, Seating, Waitstaff, Street Parking, Accepts Credit Cards.",
                "+966127323073",
                "All week: 1 PM - 2 AM.",
                "21.278449,40.413856"));
///////////////////////////////////////////////////////////////////////////////////
places.add(new Place(R.drawable.china,
                "China Restaurant",
                "Serves authentic Chinese food from the famous Sichuan cuisine by Chinese chefs.",
                "Cuisine:  Chinese, Vegetarian-Friendly.\nMeals: Lunch, Dinner.\nRestaurant features: Takeout, Seating.\nGood for:  Large groups, Families with children.",
                "+966127490372",
                "Friday: 1 PM - 12 AM.\nOther days: 12 PM - 12 AM.",
                "21.264606,40.411007"));
///////////////////////////////////////////////////////////////////////////////////
places.add(new Place(R.drawable.gusto,
                "Gusto",
                "Nice Italian food at affordable prices in a quiet ambiance.",
                "Cuisine:  Italian.\nMeals:  Lunch, Dinner.\nRestaurant features:  Takeout, Seating.\nGood for:  Large groups, Kids, Families with children.",
                "+966127444442",
                "All week: 1 PM - 1 AM.",
                "21.253650,40.410872"));
///////////////////////////////////////////////////////////////////////////////////
///////////////////////////////HOTELS///////////////////////////////////////////
places.add(new Place(R.drawable.intercontinental,
                "Intercontinental",
                "Elegant hotel with views over mountains Taif.",
                "This Taif hotel is situated at an elevation of 5,577 feet in the Hejaz Mountains, the Kingdom’s most desirable resort area. Enjoy cooler temperatures, abundant sunshine, and picturesque surroundings while taking advantage of the hotel’s heated indoor pool, tennis courts, and Hawazen restaurant. Relax in one of the 179 elegantly appointed guest rooms or explore Al Hada Mountain, Shubra Palace, and King Fahd Park. If shopping is your aim, browse local souks for spices, perfumes, and handicrafts.",
                "+966127505050",
                Place.NO_WH,
                "21.371019,40.461999"));
///////////////////////////////////////////////////////////////////////////////////
places.add(new Place(R.drawable.meridien,
                "Le Meridien Al Hada",
                "The celebrity treatment with world-class service.",
                "Situated on the highest peak of Taif’s mountain range, this hotel features a marble lobby and spacious guest accommodations. There is an indoor and outdoor swimming pool, as well as a gym and sauna.\nA buffet breakfast is served daily in the dining room with its sparkling chandeliers, paintings, and thick curtains. It takes a 15-minute drive to reach a variety of restaurants in the center.\nThe 24-hour reception staff can arrange car rentals. Taif Regional Airport is a 30-minute drive away, while Mekkah can be reached within 45 minutes.",
                "+966127541400",
                Place.NO_WH,
                "21.286632,40.392220"));
///////////////////////////////////////////////////////////////////////////////////
places.add(new Place(R.drawable.boudl,
                "Boudl Taif",
                "Located in the City of Ta’if, well known for its agriculture.",
                "Boudl Taif hotel offers air-conditioned rooms with free Wi-Fi. It has a 24-hour front desk and an elevator. Free public parking is available on site. The rooms feature a modern décor and are fitted with carpeted floors. Each includes a seating area with sofa, a flat-screen TV, and a minibar. Some rooms include a kitchenette and a dining area.\n\nTaif Regional Airport is just a 30-minute drive from Boudl Taif. Shubra Palace is 15 minutes drive away. Guests can also visit the famous Rudaf Park which is within a walking distance from the hotel.",
                "+966920000666",
                Place.NO_WH,
                "21.233985,40.411211"));
///////////////////////////////////////////////////////////////////////////////////
places.add(new Place(R.drawable.awaliv,
                "Awaliv Suites",
                "A good place to stay in Taif, close to city center with parking availability.",
                "Guests can enjoy free Wi-Fi access in the entire hotel. Ironing and luggage storage can be arranged by the 24-hour front desk. The air-conditioned rooms and suites at Awaliv have a satellite TV, a desk and a wardrobe. Each suite includes a living room with sofa, while the kitchenette offers kitchenware, a fridge, and an electric kettle.\n\nNearby restaurants and coffee shops are within walking distance from Awaliv Suites. Taif Heart Mall is 4 minutes by car. Taif Regional Airport is a 25-minute drive away. Free private parking is possible on site. ",
                "+966127319999",
                Place.NO_WH,
                "21.295604,40.429166"));
///////////////////////////////////////////////////////////////////////////////////
places.add(new Place(R.drawable.tulip,
                "Tulip Inn Taif",
                "luxury amenities including massage treatments and a fully equipped fitness center.",
                "Situated in the Taif business district, this hotel features luxury amenities including massage treatments and a fully equipped fitness center. Each guestroom is equipped with satellite TV and free Wi-Fi.\nAir-conditioned rooms at the Tulip Inn Altaif are spacious and have modern furnishings. They include a tea and coffee making facilities and have a private bathroom with a hairdryer.\n\nAl Dana restaurant serves Middle Eastern and international cuisine as well as a buffet breakfast. Drinks from the bar can be enjoyed on the terrace.\n\nTulip Inn is situated on the slopes of the Sarawat Mountains and is a 25-minute drive from Taif Airport. It offers 24-hour front desk service and free on-site private parking.",
                "+966127335533",
                Place.NO_WH,
                "21.276267,40.413683"));
///////////////////////////////////////////////////////////////////////////////////
places.add(new Place(R.drawable.ramada,
                "Ramada AL Hada Hotel and Suites",
                "Al Hada Hotel offers modern accommodation close to business establishments and theme parks.",
                "Located next to the cable car, Al Hada Hotel offers modern accommodation close to business establishments and theme parks. It features room services and a 24-hour reception desk. Rooms of the Ramada Al Hada Hotel And Suites are equipped with air conditioning and flat-screen satellite TVs. They all include bathrooms with bathtub and slippers.\n\nGuests can enjoy a selection of Middle Eastern and international cuisine, served at the restaurant of the hotel. The dishes are prepared according to the season and the freshness of the ingredients.\n\nNearby attractions include Al Rudaf Natural Park and Prophet Mohammed’s Wadi Mitna Sanctuary. Taif Regional Airport is a 30-minute drive away. ",
                "+966127545558",
                Place.NO_WH,
                "21.364348,40.267815"));
///////////////////////////////////////////////////////////////////////////////////
places.add(new Place(R.drawable.al_ward,
                "Al Ward Heritage Village",
                "provides guests with a water park. The accommodation offers a business center and room service for guests.",
                "Al Ward Heritage Village features air-conditioned accommodation in Taif. Featuring a 24-hour front desk, this property also provides guests with a water park. The accommodation offers a business center and room service for guests.\nSome rooms include a kitchenette with a microwave.\n\nThe resort offers a barbecue. Hiking is among the activities that guests can enjoy near Al Ward Heritage Village. Jouri Mall is 19 km from the accommodation. Ta'if Regional Airport is 44 km from the property. ",
                "+966555080489",
                Place.NO_WH,
                "21.120926,40.371633"));
///////////////////////////////////////////////////////////////////////////////////
places.add(new Place(R.drawable.ofoq,
                "Ofoq Al Raha Hotel Apartment",
                "Offers an indoor pool, a restaurant, and self-catering accommodations.",
                "Offering an indoor pool and a restaurant, Ofoq Al Raha Hotel Apartment offers self-catering accommodations. Free WiFi access is available in all areas. The property is a 10-minute drive away from Green Mountain Park.\nApartments at Ofoq Al Raha Hotel Apartment feature a flat-screen TV, air conditioning, and a hot tub. There is a full kitchen with a microwave and an oven.",
                Place.NO_PHONE,
                Place.NO_WH,
                "21.326061,40.434639"));
///////////////////////////////////////////////////////////////////////////////////
/////////////////////////////MUSEUMS///////////////////////////////////////////
places.add(new Place(R.drawable.shubra,
                "Shubra Palace",
                "A great historical building used by several generations of Royal families and governors of AlHijaz and Saudi Royal family.",
                "Shubra Palace is a museum in Taif. The building was completed in 1325 AH and the construction took 3 years. King Abdul-Aziz lived in the palace and King Faisal used it as a headquarters for the council of the ministry of defense and aviation.\n\nGuided tours are available here. However, bear in mind that this place is not wheelchair-friendly and you will need to go up the stairs in order to have a complete tour of the museum.",
                Place.NO_PHONE,
                "Friday: Closed.\nOther days: 9 AM - 6 PM.",
                "21.286310,40.414985"));
///////////////////////////////////////////////////////////////////////////////////
places.add(new Place(R.drawable.sharif,
                "Sharif Museum",
                "This is a collection of everything from Arabic home living crammed into a series of rooms decorated like local houses.",
                "Al-Sharif Museum is one of the museums of the Makkah Region in Taif Governorate. It was founded on the back of Meles Al-Sharif. It is a national museum inside a large building of 5000 square meters. It contains a large collection of heritage pieces of all kinds, functions, and materials. On a small market is a group of stalls or shops and make each shop for a specific craft and added to the tools and machines that belong to the craft, and the museum contains the halls of each group, such as weapons of swords, guns, daggers and spears in the hall alone, as well as coffee tools in a dedicated place and utensils Cooking in place and do Agriculture, clothing, and ornaments.",
                Place.NO_PHONE,
                "All week: 10 AM - 12 PM, 4 PM - 8 PM.",
                "21.242962,40.447022"));
///////////////////////////////////////////////////////////////////////////////////
places.add(new Place(R.drawable.okaz,
                "Okaz Market",
                "Historical museum and market.",
                "The most popular Arab gatherings to perform Hajj before Islam, a forum for thought, literature, and poetry, where there are performances of folk art in the market center, and the visitor can arrive there by his own car or accompanied by a tourist group.",
                "27 June - 13 July: 10 Am - 12 PM.",
                "+966550068777",
                "21.467267,40.645324"));
///////////////////////////////////////////////////////////////////////////////////
////////////////////////////////SHOPPING//////////////////////////////////////
places.add(new Place(R.drawable.jouri,
                "Jouri Mall",
                "Jouri shopping mall is a 5-star mall that has brought Taif to a higher level.",
                "The Mall is clean, spacious and has a good temperature control. The toilets are well accommodated and very clean. The shops are selling products of high quality. Salesmen and women are courtesy and friendly to help the customer to find what they need.\n\nIt's worthy to visit the Turkish delight shop and taste the delicious goodies. All products are fresh. The food court is really great. International food, fresh and good. The seating area is well looking after. Always clean tables and floor.",
                "Friday: 2 PM - 12 AM.\nOther days: 10 AM - 11 PM.",
                "+966920000262",
                "21.276269,40.444967"));
///////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////
places.add(new Place(R.drawable.heart_mall,
                "Taif's Heart Mall",
                "Loads of shopping to do. There is a good variety of shops, catering for all.",
                "The variety of shops are very good. Enough choice and on the top floor an ice skate ring and a lovely fancy fair for the children. Around the children's entertainment area are food stalls from French crepes, fruit juices, hamburgers, Ice cream, Arabic coffee, Small Dutch Pancakes, Cinnamon buns and a lot more. On Gate 3 ground floor is a lovely coffee shop where you can sit on the terras or inside. ",
                "Friday: 4 PM - 1 AM.\nOther days: 10 AM - 12 PM.",
                "+966920003987",
                "21.286741,40.418700"));
